# Generated by Django 5.2 on 2025-12-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Sinf"),
        ),
    ]
