# Generated by Django 5.2 on 2025-12-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField(verbose_name="Sinf")),
                ("text", models.TextField(verbose_name="Savol matni")),
                (
                    "option_a",
                    models.CharField(max_length=255, verbose_name="Variant A"),
                ),
                (
                    "option_b",
                    models.CharField(max_length=255, verbose_name="Variant B"),
                ),
                (
                    "option_c",
                    models.CharField(max_length=255, verbose_name="Variant C"),
                ),
                (
                    "option_d",
                    models.CharField(max_length=255, verbose_name="Variant D"),
                ),
                (
                    "correct",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="To‘g‘ri javob",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["grade"], name="quiz_questi_grade_bf9327_idx"),
                    models.Index(
                        fields=["subject"], name="quiz_questi_subject_30f502_idx"
                    ),
                ],
            },
        ),
    ]
