# Generated by Django 5.2 on 2025-12-30 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_testattempt_testanswer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="testanswer",
            index=models.Index(
                fields=["attempt"], name="quiz_testan_attempt_304510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testanswer",
            index=models.Index(
                fields=["question"], name="quiz_testan_questio_cf2056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testanswer",
            index=models.Index(
                fields=["is_correct"], name="quiz_testan_is_corr_d6f402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["grade", "subject"], name="quiz_testat_grade_c38a0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["correct", "duration_seconds", "created_at"],
                name="quiz_testat_correct_c97062_idx",
            ),
        ),
    ]
